<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	  <LangVersion>12</LangVersion>
      <Nullable>enable</Nullable>

  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Mono.Cecil" Version="0.10.4" />
    <PackageReference Include="MonoMod" Version="20.5.21.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MonoWeaver\MonoWeaver.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Patterns\" />
  </ItemGroup>

</Project>
